spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:kafkaui'
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  liquibase:
    change-log: 'classpath:changelog.yml'
  h2:
    console:
      enabled: true
json:
  file:
    directory: ${STORAGE_PATH:}